### ISSUE TITLE
Wrong card name

### ISSUE THREAD

**Issue by clement-tourriere** [rawrzcookie/TT2_CSV#1]
https://github.com/rawrzcookie/TT2_CSV/blob/1319ab17f1749c39f1a2e3335a1ee5f1efc347b9/csv/RaidSkillInfo.csv#L40

I guess the card name should be `Radiant Kaleidoscope` instead of `Radiant Kaliedoscope`

**Comment by rawrzcookie** [comment]
File is unedited and as-is from Gamehive. I have nothing to do with this

**Comment by clement-tourriere** [comment]
That's what I thought too ^^. That's strange because in the game and everywhere else it's correctly named `Radiant Kaleidoscope`, I changed my import script to "fix" it manually.
